=== BEST-OF-RUN ===
              generation: 49
                   nodes: 286
                   depth: 28
                    hits: 79
TOP INDIVIDUAL:



-- #1 --
                    hits: 79
             raw fitness: 79.0000
    standardized fitness: 10.0000
        adjusted fitness: 0.0909
TREE:
 (move (progn2 (move (if-food-ahead (move (move (move (if-food-ahead (progn2 (if-food-ahead (move move) left)
                                                                             (progn2 (move (if-food-ahead (move (progn2 move move))
                                                                                                          (progn2 (if-food-ahead move left)
                                                                                                                  (move (if-food-ahead move right)))))
                                                                                     (move left)))
                                                                     (move (move (progn2 (move (if-food-ahead (if-food-ahead (move (move (move (if-food-ahead (progn2 (progn2 (if-food-ahead (if-food-ahead (if-food-ahead (if-food-ahead (move move)
                                                                                                                                                                                                                                          (move move))
                                                                                                                                                                                                                           (move (progn2 move right)))
                                                                                                                                                                                                            (move (progn2 (progn2 move move)
                                                                                                                                                                                                                          (progn2 right move))))
                                                                                                                                                                                             (if-food-ahead (move (if-food-ahead (if-food-ahead move right)
                                                                                                                                                                                                                                 (if-food-ahead right right)))
                                                                                                                                                                                                            (if-food-ahead move
                                                                                                                                                                                                                           (move move))))
                                                                                                                                                                              (if-food-ahead (progn2 (move move)
                                                                                                                                                                                                     (if-food-ahead move right))
                                                                                                                                                                                             (if-food-ahead (move move)
                                                                                                                                                                                                            (move move))))
                                                                                                                                                                      (move (move left)))
                                                                                                                                                              (move (progn2 (progn2 (if-food-ahead (if-food-ahead (if-food-ahead right left)
                                                                                                                                                                                                                  (if-food-ahead move left))
                                                                                                                                                                                                   (move left))
                                                                                                                                                                                    (progn2 left left))
                                                                                                                                                                            (if-food-ahead (progn2 (progn2 move move)
                                                                                                                                                                                                   (if-food-ahead left left))
                                                                                                                                                                                           (progn2 (move (if-food-ahead (move (progn2 move move))
                                                                                                                                                                                                                        (progn2 (if-food-ahead move left)
                                                                                                                                                                                                                                (if-food-ahead (progn2 right left)
                                                                                                                                                                                                                                               (move (progn2 move move))))))
                                                                                                                                                                                                   (move left)))))))))
                                                                                                                             (progn2 (if-food-ahead move left)
                                                                                                                                     (if-food-ahead (progn2 right left)
                                                                                                                                                    (move (progn2 move move)))))
                                                                                                              (progn2 (if-food-ahead move left)
                                                                                                                      (move (if-food-ahead (progn2 (progn2 move move)
                                                                                                                                                   (if-food-ahead left left))
                                                                                                                                           (progn2 (move (if-food-ahead (move (progn2 move move))
                                                                                                                                                                        (progn2 (if-food-ahead move left)
                                                                                                                                                                                (progn2 (move (if-food-ahead (move (if-food-ahead (if-food-ahead right
                                                                                                                                                                                                                                                 (if-food-ahead left right)) move))
                                                                                                                                                                                                             (if-food-ahead left right)))
                                                                                                                                                                                        (if-food-ahead (if-food-ahead left left)
                                                                                                                                                                                                       (move (progn2 move move)))))))
                                                                                                                                                   (move left)))))))
                                                                                         (progn2 (move (progn2 (progn2 (move (if-food-ahead (if-food-ahead move move)
                                                                                                                                            (if-food-ahead left right)))
                                                                                                                       (if-food-ahead (progn2 right left)
                                                                                                                                      (move (progn2 move move))))
                                                                                                               (if-food-ahead (progn2 right left)
                                                                                                                              (move (progn2 move move)))))
                                                                                                 (if-food-ahead (progn2 right left)
                                                                                                                (move (progn2 move move)))))))))))
                                    (progn2 (if-food-ahead move left)
                                            (move (if-food-ahead move
                                                                 (progn2 move right))))))
               (progn2 (move (if-food-ahead (move (if-food-ahead (progn2 (if-food-ahead right left)
                                                                         (move (move left)))
                                                                 (move (progn2 (progn2 (if-food-ahead (move (if-food-ahead move
                                                                                                                           (move move)))
                                                                                                      (move left))
                                                                                       (if-food-ahead (move move) left))
                                                                               (move (move (progn2 right
                                                                                                   (if-food-ahead move right))))))))
                                            (if-food-ahead left right)))
                       (if-food-ahead (progn2 right left)
                                      (move (progn2 move move))))))
BEST OF RUN INDIVIDUAL:
   time taken: 400/400
food consumed: 79/89
path: 
     xxxxxx...................x......
     ...xxxx................xxx...x..
     ...x....................xxxxxx..
     ...x....................x....x..
     ...x..........x.........x....N..
     ...xxxxxxxxxxxx....xxxxxx..xxx..
     ............xxxx....x.......xxx.
     ............x.......x.......x...
     ............x.......x...........
     ............x.......x........#..
     ............x.......x...........
     ............x.......x...........
     ............x.......x........#..
     ............x.......x...........
     ............x......xx.....###...
     ............x....xxx...#........
     ............x..xxx..............
     ............x...x...............
     ............x...x.......#.......
     ............x...x..........#....
     ............x...x...............
     ............x...x...............
     .x..........x...x.........#.....
     xx..........x...x......#.......x
     xxxxxxxxxxxxx...x...............
     xx......x..xxx..x...............
     .x....xxx..x....xx..............
     .x.....xxxxxxxxxxx..............
     .x.....x........xxx.............
     .x.....x........x...............
     .xxxxxxx........................
     .....x..........................
