##########################################################################
##########################################################################
#
#	#     #
#	##   ##    ##    #    #  ######  ######     #    #       ######
#	# # # #   #  #   #   #   #       #          #    #       #
#	#  #  #  #    #  ####    #####   #####      #    #       #####
#	#     #  ######  #  #    #       #          #    #       #
#	#     #  #    #  #   #   #       #          #    #       #
#	#     #  #    #  #    #  ######  #          #    ######  ######
#
##########################################################################
##########################################################################
# Makefile for the GP project
#
# History
# 4  Sep 97  Initial version
# 12 Nov 97  Changed names of source files 
# 10 Apr 98  Tidy up an unify source files
#########################################################################
##########################################################################

include		../Makefile.ini

TARGET1		= gpsc 
TARGET2		= ntrees

OPTFLAGS        = -O3

OBJS		= gpsc.o scsm.o 

CCC             = g++
CFLAGS		= -Wall -I. $(OPTFLAGS) 
CPPFLAGS	= -I$(GPINCLUDE) -I. $(OPTFLAGS) 
CCFLAGS         = -Wall
LDFLAGS		= $(OVERALLLDFLAGS) -L$(GPLIB) -lgp -lm

all : $(TARGET1) 

# Implicit rule how to compile
.cc.o:
	$(CCC) $(CPPFLAGS) $(CCFLAGS) -c $<


all: $(TARGET) $(OBJS) $(TARGET2)

$(TARGET1) : $(OBJS) $(GPLIBFILE)
	$(CCC) -o $(TARGET1) $(OBJS) $(LDFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) data.* *~

superclean: clean
	rm -f $(TARGET)

strip:
	strip $(OBJS) $(TARGET1) $(TARGET2)


# File dependencies
gpsc.o: gpsc.cc ../include/scsm.h ../include/gpsc.h ../include/gpconfig.h ../include/gp.h nodeset.h
scsm.o : scsm.cc ../include/scsm.h problem.h

ntrees : ntrees.cc

backup:
	tar cvf backup_tarfile.`date +%d%m%y`.tar *


















